// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gm
double gm(std::vector<double> const& data);
RcppExport SEXP robCompositions_gm(SEXP dataSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<double> const& >::type data(dataSEXP);
    __result = Rcpp::wrap(gm(data));
    return __result;
END_RCPP
}
