# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title
#' gmean
#' @description
#' This function calculates the geometric mean.
#' 
#' @param data a vector 
#' 
#' @details
#' \code{gm} calculates the geometric mean for all positive entries of a vector. It is implemented
#' in C++ and accounts for over- and underflows.
#' @export
#' @author Matthias Templ
#' @examples
#' gm(c(3,5,3,6,7))
gm <- function(data) {
    .Call('robCompositions_gm', PACKAGE = 'robCompositions', data)
}

